Add code to deploy openstack-hypervisor
openstack-snaps/snap-openstack pull request #18
Opened 2023-04-05 18:31 UTC by gnuoy

Add code to deploy the openstack-hypervisor to machine 0 in the controller model.

2023-04-05 19:42 UTC, gboutry commented on cloud/etc/deploy-openstack-hypervisor/backend.tf
> +}
```suggestion
```

2023-04-05 19:42 UTC, gboutry commented on cloud/etc/deploy-openstack-hypervisor/main.tf
> +}
Shouldn't the different offers be created in `deploy-openstack` plan ?

Edit: ok, you can't reference already existing offers at this moment in juju terraform provider

2023-04-05 19:42 UTC, gboutry commented on sunbeam/commands/bootstrap.py
> +        plan4.append(DeployHypervisorStep(tfhelper_hypervisor_deploy, jhelper))
I think Hypervisor can follow the same pattern as Microk8s, and be deployed as an "unit-less" application at first, and then add units ? (only it's on converged + compute instead of converged + control)

I think there will be a problem with scaling up with the current handling of the TF application

2023-04-06 06:56 UTC, hemanthnakkina commented on sunbeam/commands/hypervisor.py
> +                "placement": 0,
Will it be better to get machine id from cluster DB?

2023-04-06 06:56 UTC, hemanthnakkina commented on sunbeam/commands/hypervisor.py
> +                "charm_channel": "yoga/edge",
For channels, microk8s set the defaults in terraform files. We need to figure out the best place - snap config or ?

2023-04-06 06:56 UTC, hemanthnakkina commented on sunbeam/commands/bootstrap.py
> +        plan4.append(DeployHypervisorStep(tfhelper_hypervisor_deploy, jhelper))
Agree with @gboutry, Adding openstack-hypervisor application during bootstrap process even if the node is control. And add units in bootstrap/join commands based on role of the node.

2023-04-06 08:24 UTC, gboutry commented
Something I forgot, since you need Juju 3.2, can you raise the lib version in the `requirements.txt` ?

2023-04-06 11:09 UTC, hemanthnakkina requested changes

2023-04-06 11:09 UTC, hemanthnakkina commented on sunbeam/commands/hypervisor.py
> +    def has_prompts(self) -> bool:
nit: Can we remove has_prompts and is_skip functions as they are same as Base class BaseStep.

2023-04-06 11:20 UTC, hemanthnakkina approved these changes

2023-04-06 11:21 UTC, merged