Add heat plugin
openstack-snaps/snap-openstack pull request #182
Opened 2023-07-24 06:43 UTC by hemanthnakkina

Add heat plugin with terraform plans in
sunbeam-terraform repo.

Depends-On: https://github.com/openstack-snaps/sunbeam-terraform/pull/34
Depends-On: https://github.com/openstack-snaps/snap-openstack/pull/181

2023-07-26 12:30 UTC, gboutry requested changes

2023-07-26 12:30 UTC, gboutry commented on sunbeam-python/sunbeam/plugins/heat/plugin.py
> +            apps.extend(["heat-mysql", "heat-cfn-mysql"])
```suggestion
            apps.extend(["heat-mysql"])
```

This is not true since the changes on the PR

2023-07-26 15:22 UTC, gboutry commented on sunbeam-python/sunbeam/plugins/heat/plugin.py
> +            "heat-channel": "latest/edge",
Should be updated since the track was created

```suggestion
            "heat-channel": "2023.1/edge",
```

2023-07-27 02:04 UTC, hemanthnakkina commented on sunbeam-python/sunbeam/plugins/heat/plugin.py
> +            apps.extend(["heat-mysql", "heat-cfn-mysql"])
Good catch, fixed now.

2023-07-27 02:05 UTC, hemanthnakkina commented on sunbeam-python/sunbeam/plugins/heat/plugin.py
> +            "heat-channel": "latest/edge",
2023.1/edge not released when the PR is submitted. Now it is available, changed the heat-channel.

2023-07-27 07:03 UTC, gboutry approved these changes
LGTM

2023-07-27 07:03 UTC, merged