Add configure step
openstack-snaps/snap-openstack pull request #31
Opened 2023-04-27 09:12 UTC by gnuoy

This change adds a configure step that can be run after bootstrap. The configure step will optionally setup default images, flavors etc in the cloud as well as configuring networking.

The last step in the plan configure executes runs an action on the openstack-hypervisor charm to set unit specific values such as which nic to use for North/South traffic. This change also adds that step to the node join command.

Depends-On: https://review.opendev.org/c/openstack/charm-openstack-hypervisor/+/881493

2023-04-28 08:12 UTC, hemanthnakkina requested changes

2023-04-28 08:12 UTC, hemanthnakkina commented on sunbeam/commands/configure.py
> +        SetLocalHypervisorOptions(name, jhelper),
Why do we need this in configure? Instead can we add calling this function in bootstrap if --role compute is enabled.

2023-04-28 08:12 UTC, hemanthnakkina commented on sunbeam/commands/configure.py
> +    action_result = run_sync(jhelper.run_action(unit, model, action_cmd))
Do we need to catch exceptions where ever run_action is executed?

2023-04-28 08:12 UTC, hemanthnakkina commented on sunbeam/commands/configure.py
> +            raise click.ClickException(_message)
Should return ResultType.FAILED instead of ClickException

2023-04-28 08:12 UTC, hemanthnakkina commented on sunbeam/utils.py
> +def get_free_nics() -> list:
Probably move this logic to charm and expose an action list-interfaces in charm. This will align with juju spaces as well in future.

Not required for this PR but something to keep in mind for future.

2023-05-01 14:28 UTC, gnuoy commented on sunbeam/commands/configure.py
> +        SetLocalHypervisorOptions(name, jhelper),
As discussed there is user may want to bootstrap microstack and then do the network wiring themselves

2023-05-01 15:21 UTC, hemanthnakkina approved these changes
LGTM

2023-05-01 15:21 UTC, merged